name: CI/CD Pipeline

on:
  push:
    branches:
      - staging

permissions:
  contents: write
  pull-requests: write

jobs:
  validate-flask:
    name: Validate Application Flask
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  create-pr-develop:
    name: Create Pull Request to Develop
    needs: validate-flask
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Garante que todo o histórico da branch seja mantido

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
          branch: staging
          title: "Automated PR: Staging → Develop"
          commit-message: "Automated PR to merge staging into develop"
          body: "This PR foi criado automaticamente para mesclar staging em develop. Favor revisar antes de aprovar."
          draft: false
          delete-branch: false
          assignees: ${{ github.actor }}
          reviewers: ${{ github.actor }}
          labels: "auto-generated"
          always-create: true
